name: Chat GPT Auto Review

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Chat GPT auto review
      uses: JavaRip/gpt-code-review@v0.26
      with:
        # Add required inputs for the JavaRip/gpt-code-review a31Gction here
        # For example, if it requires a GitHub token, you can pass it like this:
        # github-token: ${{ secrets.GITHUB_TOKEN }}
        # Replace 'github-token' with the actual input name the action expects
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        OPEN_API_KEY: ${{ secrets.OPEN_API_KEY}}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO: ${{ github.repository }}
